const userExamples = [
  {
    name: 'Juan Pérez',
    username: 'juanperez',
    email: 'juanperez@deletrar.com',
    description: 'Amante de la literatura y el mate.',
    password: 'password123',
  },
  {
    name: 'María González',
    username: 'mariagonzalez',
    email: 'mariagonzalez@deletrar.com',
    photo: 'default.jpg',
    description: 'Escritora de cuentos cortos y poesía.',
    followers: [],
    followerAmount: 0,
    following: [],
    savedPosts: [],
    savedCollections: [],
    role: 'user',
    password: 'securepass',
    passwordConfirm: 'securepass',
    active: true,
    createdAt: '2024-01-19T15:30:00Z',
    settings: {
      publicAccount: true,
      receivingInvitationRequests: true,
      publicEditing: false,
    },
    notes: [],
    documentType: 'user',
  },
  {
    name: 'Lucía Ramírez',
    username: 'luciaramirez',
    email: 'luciaramirez@deletrar.com',
    photo: 'default.jpg',
    description: 'Editora freelance y fanática del tango.',
    followers: [],
    followerAmount: 0,
    following: [],
    savedPosts: [],
    savedCollections: [],
    role: 'user',
    password: 'mypassword',
    passwordConfirm: 'mypassword',
    active: true,
    createdAt: '2024-01-18T18:45:00Z',
    settings: {
      publicAccount: true,
      receivingInvitationRequests: true,
      publicEditing: false,
    },
    notes: [],
    documentType: 'user',
  },
  {
    name: 'Carlos López',
    username: 'carloslopez',
    email: 'carloslopez@deletrar.com',
    photo: 'default.jpg',
    description: 'Periodista y amante de los viajes.',
    followers: [],
    followerAmount: 0,
    following: [],
    savedPosts: [],
    savedCollections: [],
    role: 'user',
    password: 'topsecret',
    passwordConfirm: 'topsecret',
    active: true,
    createdAt: '2024-01-17T12:00:00Z',
    settings: {
      publicAccount: true,
      receivingInvitationRequests: true,
      publicEditing: false,
    },
    notes: [],
    documentType: 'user',
  },
  {
    name: 'Sofía Martínez',
    username: 'sofiamartinez',
    email: 'sofiamartinez@deletrar.com',
    photo: 'default.jpg',
    description: 'Diseñadora gráfica apasionada por el arte.',
    followers: [],
    followerAmount: 0,
    following: [],
    savedPosts: [],
    savedCollections: [],
    role: 'user',
    password: 'mypassword',
    passwordConfirm: 'mypassword',
    active: true,
    createdAt: '2024-01-16T11:20:00Z',
    settings: {
      publicAccount: true,
      receivingInvitationRequests: true,
      publicEditing: false,
    },
    notes: [],
    documentType: 'user',
  },
  {
    name: 'Diego Fernández',
    username: 'diegofernandez',
    email: 'diegofernandez@deletrar.com',
    photo: 'default.jpg',
    description:
      'Apasionado por la tecnología y los libros de ciencia ficción.',
    followers: [],
    followerAmount: 0,
    following: [],
    savedPosts: [],
    savedCollections: [],
    role: 'user',
    password: 'supersecure',
    passwordConfirm: 'supersecure',
    active: true,
    createdAt: '2024-01-15T10:00:00Z',
    settings: {
      publicAccount: true,
      receivingInvitationRequests: true,
      publicEditing: false,
    },
    notes: [],
    documentType: 'user',
  },
];

const names = [
  'Martín López',
  'Lucía Fernández',
  'Joaquín Gómez',
  'Sofía Ramírez',
  'Carlos Álvarez',
  'María González',
  'Agustín Pérez',
  'Valentina Torres',
  'Nicolás Rodríguez',
  'Paula Martínez',
  'Diego Morales',
  'Camila Herrera',
  'Lautaro Díaz',
  'Julieta Castro',
  'Franco Vega',
  'Daniela Romero',
  'Mateo Méndez',
  'Emilia Navarro',
  'Santiago Ortiz',
  'Florencia Ríos',
  'Tomás Acosta',
  'Pilar Suárez',
  'Andrés Molina',
  'Victoria Ibáñez',
  'Felipe Ponce',
  'Elena Varela',
  'Gonzalo Reyes',
  'Ana Domínguez',
  'Iván Bustamante',
  'Laura Villalba',
];

const descriptions = [
  'Amante de la literatura clásica argentina',
  'Fanática de los poemas gauchescos',
  'Escritor amateur de novelas de misterio',
  'Apasionada por los cuentos cortos',
  'Coleccionista de libros antiguos',
  'Editora de libros de fantasía',
  'Crítico literario especializado en poesía',
  'Exploradora de nuevos talentos literarios',
  'Entusiasta de la narrativa histórica',
  'Investigadora de mitos y leyendas locales',
  'Autor de thrillers psicológicos',
  'Escritora de relatos fantásticos',
  'Profesor de literatura en secundaria',
  'Ilustradora de libros infantiles',
  'Amante de los clásicos universales',
  'Investigadora de corrientes literarias modernas',
  'Redactor de artículos académicos',
  'Lector ávido de novelas gráficas',
  'Traductor de textos antiguos',
  'Escritora de microcuentos',
  'Fanático de los ensayos filosóficos',
  'Creadora de talleres de escritura',
  'Editor de antologías de cuentos',
  'Investigadora en lingüística',
  'Narradora oral en eventos culturales',
  'Especialista en literatura latinoamericana',
  'Autor de novelas románticas',
  'Poeta urbana y activista cultural',
  'Organizador de ferias del libro',
  'Promotora de la lectura en comunidades rurales',
];

// eslint-disable-next-line no-unused-vars
const anonymous = {
  _id: {
    $oid: '6723e42d16f286f0d94d6219',
  },
  name: 'Lector Anónimo',
  username: 'lectoranonimo',
  email: 'anonymous@fantasydeletrarweb.com',
  photo: 'anonymous.png',
  following: [],
  role: 'user',
  password: '$2a$12$kn1UNuNo0Hp59QwtvHHtNOFaLze0i1eYjM7eGadEG9KtIjTdS6z1m',
  active: false,
  createdAt: {
    $date: '2024-05-02T20:44:14.983Z',
  },
  settings: {
    receivingInvitationRequests: true,
  },
  notes: [],
  __v: 0,
  followers: [],
  followerAmount: 0,
  documentType: 'user',
};

module.exports = { descriptions, names, userExamples };
